
################ NGINX Container ################
front:
  restart: always
  container_name: nginx
  build: ./docker/container/nginx/
  ports:
    - 80:80
    - 443:443
    - 9000:9000
  volumes:
    - ./:/var/www/
    - ./docker/config/nginx/conf.d:/etc/nginx/conf.d
    - ./docker/log/nginx:/var/log/nginx
  links:
    - php-fpm
    - phpmyadmin:phpmyadmin
#    - phppgadmin:phppgadmin
################ NGINX Container END; ################


################ PHP-FPM Container ################
php-fpm:
  restart: always
  container_name: php-fpm
  build: ./docker/container/php/7.1/
  volumes:
    - ./:/var/www/
    - ./docker/config/php/7.1/php.ini:/usr/local/etc/php/php.ini
    - ./docker/config/php/7.1/upload.ini:/usr/local/etc/php/upload.ini
  links:
    - memcached:memcached
    - redis:redis
    - mongo:mongo
    - mysql:mysql
#    - postgres:postgres
################ PHP-FPM Container END; ################


################ MYSQL Container ################
mysql:
  restart: always
  container_name: mysql
  build: ./docker/container/mysql/
  ports:
    - 3306:3306
  environment:
    MYSQL_ROOT_PASSWORD: 1
  volumes:
    - ./docker/data/mysql:/var/lib/mysql
    - ./docker/log/mysql:/var/log/mysql
################ MYSQL Container END; ################


################ PHPMYADMIN Container ################
# При первом входе введите в поле Server (Сервер) - название контейнера БД, в нашем случае это mysql
# введите имя логина - root пароль - MYSQL_ROOT_PASSWORD
# создайте учетную запись для обслуживания БД (Примечание host нужно выбрать "любой: %")
phpmyadmin:
  restart: always
  container_name: phpmyadmin
  build: ./docker/container/phpmyadmin/
  links:
    - mysql:mysql
  ports:
      - 8181:80
  environment:
      MYSQL_ROOT_PASSWORD: 1
      MYSQL_USER: ser
      MYSQL_PASSWORD: ser
      PMA_ARBITRARY: 1
  volumes:
    - ./docker/data/phpmyadmin/sessions:/sessions
################ PHPMYADMIN Container END; ################


################ PostgreSQL Container ################
#postgres:
#  restart: always
#  container_name: postgres
#  build: ./docker/container/postgres/
#  ports:
#    - 5432:5432
#  environment:
#    POSTGRES_USER: ser
#    POSTGRES_PASSWORD: ser
#  volumes:
#    - ./docker/data/postgres:/var/lib/postgresql/data
#    - ./docker/log/postgres:/var/log/postgresql
################ PostgreSQL Container END; ################

################ PGAdmin Container ################
### Выберите на свой вкус один из двух ###
#phppgadmin:
#  restart: always
#  container_name: pgadmin
#  build: ./docker/container/phppgadmin/
#  environment:
#    - POSTGRESQL_HOST=postgres
#    - POSTGRESQL_PORT=5432
#    - POSTGRESQL_DEFAULT_DB=postgres
#  ports:
#    - 8182:80
#  links:
#    - postgres:postgres
### Выберите на свой вкус один из двух ###
#phppgadmin:
#  restart: always
#  container_name: pgadmin
#  build: ./docker/container/pgadmin/
#  ports:
#    - 8182:5050
#  links:
#    - postgres:postgres
#  volumes:
#      - ./docker/data/phppgadmin:/root/.pgadmin
################ PGAdmin Container ################

################ MongoDB Container ################
mongo:
  restart: always
  container_name: mongo
  build: ./docker/container/mongo/
  ports:
    - 27017:27017
  volumes:
    - ./docker/data/mongo:/data/db
################ MongoDB Container END; ################

################ Redis Container ################
redis:
  restart: always
  container_name: redis
  build: ./docker/container/redis/
  ports:
    - 6379:6379
  volumes:
    - ./docker/data/redis:/data
################ MongoDB Container END; ################

################ PHPRedisAdmin Container ################
#phpredisadmin:
#  restart: always
#  container_name: phpredisadmin
#  build: ./docker/container/phpredisadmin/
#  ports:
#    - 8185:80
#  environment:
#    - REDIS_1_HOST=redis
#  links:
#    - redis
################ PHPRedisAdmin Container END; ################

################ PHPRedisAdmin Container ################
memcached:
  restart: always
  container_name: memcached
  build: ./docker/container/memcached
  volumes:
      - ./docker/data/memcached:/var/lib/memcached
  ports:
      - 11211:11211
################ PHPRedisAdmin Container END; ################